//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerAssignment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assign
    {
        public int Id { get; set; }
        public int R_Id { get; set; }
        public int EmpId { get; set; }
        public string Status { get; set; }
    
        public virtual Request Request { get; set; }
        public virtual User User { get; set; }
    }
}
