//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHungerAssignment.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Request()
        {
            this.Assigns = new HashSet<Assign>();
        }
    
        public int R_Id { get; set; }
        public string R_Name { get; set; }
        public string IteamName { get; set; }
        public int Quantity { get; set; }
        public string Location { get; set; }
        public string ExDate { get; set; }
        public string AssignEmployee { get; set; }
        public string Status { get; set; }
        public int RestaurantId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assign> Assigns { get; set; }
        public virtual User User { get; set; }
    }
}
